load("@rules_python//python/uv:lock.bzl", "lock")

lock(
    name = "requirements",
    srcs = ["requirements.in"],
    out = "requirements.txt",
)

alias(
    name = "serve",
    actual = "//docs:docs.serve",
    visibility = ["//visibility:public"],
)

alias(
    name = "ls",
    actual = "//docs:_docs/_sources",
    visibility = ["//visibility:public"],
)

alias(
    name = "wheel",
    actual = "//md3:wheel",
    visibility = ["//visibility:public"],
)

alias(
    name = "publish",
    actual = "//md3:wheel.publish",
    visibility = ["//visibility:public"],
)
